### ISSUE TITLE
New Version of protobuf Produces an Error on Init

### ISSUE THREAD

**Issue by konfortes** [signalfx/signalfx-python#125] opened 2022-05-26 11:51 UTC
Hey guys,
I'm getting this runtime error when trying to initialize the client:
```
  File "/home/jenkins/workspace/common-theme_common-main_PR-3310/common/.nox/test/lib/python3.8/site-packages/signalfx/__init__.py", line 103, in ingest
    from . import ingest
  File "/home/jenkins/workspace/common-theme_common-main_PR-3310/common/.nox/test/lib/python3.8/site-packages/signalfx/ingest.py", line 21, in <module>
    from .generated_protocol_buffers \
  File "/home/jenkins/workspace/common-theme_common-main_PR-3310/common/.nox/test/lib/python3.8/site-packages/signalfx/generated_protocol_buffers/signal_fx_protocol_buffers_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/jenkins/workspace/common-theme_common-main_PR-3310/common/.nox/test/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

It seems like a new stable version or protobuf (`4.21.0`) was release ~11h ago and the protobuf requirement is defined with `>=3.0.0` so I guess this error has to do with that new protobuf version.

Will appreciate any kind of help. Thanks

**Comment by jdyke** [comment] 2022-05-26 13:47
Looks like the newest protobuf broke a lot of things. We see this error as well using signalfx

https://github.com/protocolbuffers/protobuf/issues/10051

**Comment by meghaddn** [comment] 2022-05-27 19:36
Could someone please create a new release with the merged fix. Thank you!

**Comment by jeffreyc-splunk** [comment] 2022-06-02 19:28
1.1.15 released to pypi

**Comment by threewordphrase** [comment] 2022-10-18 21:41
The fix merged in #126 , pinning to `==3.20.1`, is conflicting with [google-api-core's pin on](https://github.com/googleapis/python-api-core/pull/459/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R33) `!=3.20.1`.

The original problem here looks like it was caused by a specific new problem with a specific new protobuf version. Why was it pinned exactly? Why couldn't the fix for signalfx be an additional `<4.21.0` pin?

This is causing problems for our pip-compile workflows and unnecessary pinning by pip packages does against python best practices.

**Comment by threewordphrase** [comment] 2022-10-18 21:57
Opened #132

**Comment by atoulme** [comment] 2022-11-02 15:54
Closing as #132 is now fixed, and a new release is in the process of being cut.

**Closed by atoulme** 2022-11-02 15:54 UTC
